{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"_dlLwrSghRfG","executionInfo":{"status":"ok","timestamp":1717123270076,"user_tz":420,"elapsed":20785,"user":{"displayName":"Zhiyuan Li","userId":"17007331585663379367"}},"outputId":"ec3b09c2-d06c-4f44-8c2a-1ee89ef5f2f5"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","\n","drive.mount('/content/drive')\n","\n","# TODO: Enter the path in your Drive of the assignment.\n","# e.g. 'cs231n/assignments/assignment3/'\n","FOLDERNAME = 'cs231n/assignments/assignment3/'\n","\n","assert FOLDERNAME is not None, \"[!] Enter the foldername.\""]},{"cell_type":"markdown","metadata":{"id":"0AFzUg2ghRfS"},"source":["# Collect Submission - Zip + Generate PDF\n","\n","<font color=\"red\">**Note:** Remember to execute ALL notebooks' cells before this step. We won't be regrading missing cell outputs.</font>\n","\n","Run this notebook once you have completed all the other notebooks.\n","\n","It will:\n","\n","* Generate a zip file of your code (`.py` and `.ipynb`) called `a3_code_submission.zip`.\n","* Convert all notebooks into a single PDF file called `a3_inline_submission.pdf`.\n","\n","If your submission for this step was successful, you should see the following display message:\n","\n","`### Done! Please submit a3_code_submission.zip and a3_inline_submission.pdf to Gradescope. ###`\n","\n","Make sure to download the zip and pdf file locally to your computer, then submit to Gradescope. Congrats on successfully completing the assignment!"]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"nlNoXBezhRfZ","executionInfo":{"status":"ok","timestamp":1717123310096,"user_tz":420,"elapsed":37014,"user":{"displayName":"Zhiyuan Li","userId":"17007331585663379367"}},"outputId":"58628c94-547b-4189-ba75-6d1dc682bafb"},"outputs":[{"output_type":"stream","name":"stdout","text":["/content/drive/My Drive/cs231n/assignments/assignment3\n","Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]\n","Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]\n","Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease\n","Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease\n","Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]\n","Hit:6 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease\n","Get:7 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,084 kB]\n","Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease\n","Get:9 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1,858 kB]\n","Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]\n","Get:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease [24.3 kB]\n","Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease\n","Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,377 kB]\n","Get:14 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy/main amd64 Packages [47.6 kB]\n","Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,129 kB]\n","Fetched 6,907 kB in 2s (3,274 kB/s)\n","Reading package lists... Done\n","Reading package lists... Done\n","Building dependency tree... Done\n","Reading state information... Done\n","E: Unable to locate package texlive-generic-recommended\n","Collecting PyPDF2\n","  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m232.6/232.6 kB\u001b[0m \u001b[31m5.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: PyPDF2\n","Successfully installed PyPDF2-3.0.1\n","### Zipping file ###\n","### Creating PDFs ###\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.10/dist-packages/jupyter_core/application.py\", line 283, in launch_instance\n","    super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF RNN_Captioning.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.10/dist-packages/jupyter_core/application.py\", line 283, in launch_instance\n","    super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF Transformer_Captioning.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.10/dist-packages/jupyter_core/application.py\", line 283, in launch_instance\n","    super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.10/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF Generative_Adversarial_Networks.ipynb.\n","Traceback (most recent call last):\n","  File \"/content/drive/My Drive/cs231n/assignments/assignment3/makepdf.py\", line 45, in <module>\n","    main(args.notebooks, args.pdf_filename)\n","  File \"/content/drive/My Drive/cs231n/assignments/assignment3/makepdf.py\", line 31, in main\n","    merger.append(pdf)\n","  File \"/usr/local/lib/python3.10/dist-packages/PyPDF2/_utils.py\", line 417, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/PyPDF2/_merger.py\", line 319, in append\n","    self.merge(len(self.pages), fileobj, outline_item, pages, import_outline)\n","  File \"/usr/local/lib/python3.10/dist-packages/PyPDF2/_utils.py\", line 417, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/PyPDF2/_merger.py\", line 194, in merge\n","    stream, encryption_obj = self._create_stream(fileobj)\n","  File \"/usr/local/lib/python3.10/dist-packages/PyPDF2/_merger.py\", line 263, in _create_stream\n","    stream = FileIO(fileobj, \"rb\")\n","FileNotFoundError: [Errno 2] No such file or directory: 'RNN_Captioning.pdf'\n"]}],"source":["%cd /content/drive/My\\ Drive/$FOLDERNAME\n","!sudo apt-get update\n","!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended\n","!pip install PyPDF2\n","!bash collectSubmission.sh"]}],"metadata":{"colab":{"provenance":[]},"language_info":{"name":"python"},"kernelspec":{"name":"python3","display_name":"Python 3"}},"nbformat":4,"nbformat_minor":0}